test: False

Training1_trials_con_con_con: 0
Training1_trials_inc1_inc1_inc1: 0
Training1_trials_inc1_inc2_inc1: 0
Training1_trials_inc1_inc2_inc3: 0
Training1_trials_neu_neu_neu: 10

Training2_trials_con_con_con: 15
Training2_trials_inc1_inc1_inc1: 5
Training2_trials_inc1_inc2_inc1: 5
Training2_trials_inc1_inc2_inc3: 5
Training2_trials_neu_neu_neu: 0

Training_Resp_time: 4
Training_Wait_time: 1

Number_of_blocks: 2
Experiment_trials_con_con_con: 240
Experiment_trials_inc1_inc1_inc1: 80
Experiment_trials_inc1_inc2_inc1: 80
Experiment_trials_inc1_inc2_inc3: 80
Experiment_trials_neu_neu_neu: 0

Experiment_Resp_time: 3
Experiment_Wait_time: 1

Jitter: 1

Fix_time: 1
Feedb: True
Feedb_time: 1

words_dist: 40

# ophthalmic_procedure: False